### ISSUE TITLE
UI not fitting for MacBook Air (2018 model with high res screen)

### ISSUE THREAD

**Issue by bigcookie** [Mikiya83/hbs_decipher#10]
Hi, I wanted to checkout the tool (thanks for creating it!!!). Attached the screenshot from my MacBook. It would be cool, if the window would be resizable in case resolution/DPI detection is difficult.
Please note that I simply downloaded the app and started it. 

according to system preferences, Java 8 Update 231 is installed.

<img width="728" alt="Screenshot 2020-02-07 at 15 12 49" src="https://user-images.githubusercontent.com/2866102/74036685-06cd8400-49bd-11ea-9ef3-61e4748c5b6c.png">

**Comment by Mikiya83** [comment]
Hi
As i said in the readme, you can enable resizing : 

> Note If you have visual problem :
You can start the GUI as a resizable window, with "r" command-line argument, or simply create a file "resizeEnable" in the same directory as hybrid_backup_sync_decipher_XXX_gui.jar.

Please tell me if your problem is solved with this.

**Comment by bigcookie** [comment]
I am sorry for this. Now I remember reading it before downloading, but it took a few days to test... YES, it works. I use the file option. Thanks again.
