### ISSUE TITLE
Decypher filename with openssl

### ISSUE THREAD

**Issue by damoiser** [Mikiya83/hbs_decipher#11]
Hi, this is not related as an issue on your project, but maybe you can provide help as well given the application you developed.

I am trying to write down a script to decrypt the HBS client encrypted files, for the file content this work well:
```
openssl enc -d -aes-256-cbc -k $pass -in $encrypted__file -out $decrypted_file
# if files are compressed add
gunzip -k $decrypted_file.gz
```

However I am struggling decrypting the filename, is the the "archive description" or the "archive id" key/value? Which `openssl` command do you suggest to use?

Thanks

**Comment by Mikiya83** [comment]
Hi !
Sorry but i don't know well the openssl part, i focused on the "proprietary" part of the QNAP tool... 
Good luck with your commands !

**Comment by damoiser** [comment]
Hi @Mikiya83 - thanks for your answer, I will try ;-)
