### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by alexkazik** [Mikiya83/hbs_decipher#2]
When a file is compressed by hbs then this tool is unable to decrypt it.
Could you add that feature?
(The filename is identical to the original, unlike when compressing a backup job where a qnap.bz2 is added.)

Additionally it would be nice to have a in-place decryption (decrypt to temp file in same directory, if all is ok: "mv temp orig")?

**Comment by Mikiya83** [comment]
Hi
About the compression feature, i have to study how it's done and what that imply. I don't know when they added this feature, i missed it.
About the in-place decryption, i'm not a fan of the idea... Users often use Dropbox/GDrive or similar services with auto-sync tool, so in-place decryption on the user pc will erase encrypted data with plain data directly on cloud servers without user realise it.
Maybe with a warning message but it's not a priority, it's easy to do the mv manually (or scripted) after the decryption.

**Comment by alexkazik** [comment]
Thanks for your work on the tool.

About in-place: I meant only as an option, not default. But I can see your concern - maybe an option only for cli?

**Comment by Mikiya83** [comment]
After some researches, compression use GZIP and has its own boolean in header to automatically detect it so it should be feasible. I will update this issue asap.

**Comment by Mikiya83** [comment]
Compression should be ok with 8e1fd9dbce32eed3079e505def2a23133f64bb7f , i will release a compiled version soon
edit : compiled version available !
