### ISSUE TITLE
ShortBufferException in Android

### ISSUE THREAD

**Issue by Sky-84** [Mikiya83/hbs_decipher#7]
Hi Yoann,
As I "promised" in the QNAP forum :), I'm almost finished the development of the Android app as a porting of your GUI, but I noticed that files bigger than 1KB (I don't know the exactly threshold, I guess more or less 256B) are not properly deciphered. The decryption process seems to be completed well but the deciphered files don't work and seems to have the same size of 291B (I tested different source files with different size).
I tried to understand where the issue comes from and I found a lot of errors at line 391 of QNAPFileDecrypterEngine (1.4.2) in this piece of code:

```
while (!done) {
	inLength = inputStream.read(inBytes);
	if (inLength == blockSize) {
		try {
			int outLength = dcipher.update(inBytes, 0, blockSize, outBytes);
			outputStream.write(outBytes, 0, outLength);
**
		} catch (ShortBufferException e) {
			e.printStackTrace();
		}
**
	} else
		done = true;
}
```

The error chain starts with ShortBufferException and the expression "256 < 272".
I'm absolutely available to support you to find a solution and to discuss in deep if necessary.
Regards.

**Comment by Mikiya83** [comment]
Hello
I check this asap. If you try to use the same files on Desktop version, do you also get errors ?

**Comment by Sky-84** [comment]
> 
> 
> Hello
> I check this asap. If you try to use the same files on Desktop version, do you also get errors ?

The desktop version works perfectly with all files I tested. 
Moreover I don't receive any errors compiling the class directly in the Android environment within the app (instead of import jar lib file). I do suppose there could be a incompatibility with Apache Commons lib, but it's only an hypothesis.

**Comment by Mikiya83** [comment]
Maybe... Even in Desktop version i want to remove this lib (to have as less as possible dependencies), but it requires some change in Base64 and Hex handling.

**Comment by Mikiya83** [comment]
Can you try to import this JAR ? it does not require apache commons-codec, i've done quick tests on Desktop version, it seems ok, so tell me if Android is better with it.
https://yoann-tritz.fr/documents/hybrid_backup_sync_decipher_1.4.4.jar

**Comment by Sky-84** [comment]
> Can you try to import this JAR ? it does not require apache commons-codec, i've done quick tests on Desktop version, it seems ok, so tell me if Android is better with it.
> https://yoann-tritz.fr/documents/hybrid_backup_sync_decipher_1.4.4.jar

Unfortunately the result is the same.
In attach the logs in verbose mode deciphering a txt file of about 1KB. With a bigger file the error chain repeat itself many times till reaching the end of file, I guess.
What kind of information, that I can see in the debugger, can I provide you? Or could you build an other jar lib with more "verbose mode" in order to get more info in the logs?
[logs_20190129_2146.txt](https://github.com/Mikiya83/hbs_decipher/files/2809626/logs_20190129_2146.txt)

**Comment by Mikiya83** [comment]
I find it ! 
It's related to : https://blog.osom.info/2014/07/symmetric-encryption-issue-in-android-43.html , caused by new Android crypto provider since 4.3 and even Signal app had this problem too... I fix it asap.

**Comment by Mikiya83** [comment]
Try this jar (with verbose mode if possible) : 
https://yoann-tritz.fr/documents/hybrid_backup_sync_decipher_1.4.4_debug.jar

**Comment by Sky-84** [comment]
Oh yeah, it works ;)!!
Here the logs:
```
I/System.out: Reading header values...
    Read file version 2 !
I/System.out: Decipher file...
W/System.err: Use provider : AndroidOpenSSL - Use block cipher size : 16 - Use buffer block size : 256 - Use Output size : 272
I/System.out: Sizes ok, decipher appunti.txt successfull !
```
In attach the first "beta" release of the apk you can you use to do some tests if you want.
Thanks a lot, I really appreciated your work :).

[hbs_decipher_for_Android_v0.1.zip](https://github.com/Mikiya83/hbs_decipher/files/2810091/hbs_decipher_for_Android_v0.1.zip)

**Comment by Mikiya83** [comment]
Thanks i will try it asap and tell you if i encounter any bugs ! ;)
