### ISSUE TITLE
GUI window issue

### ISSUE THREAD

**Issue by PhilD1307** [Mikiya83/hbs_decipher#9]
Firstly thank you for putting this tool together.  As is said elsewhere having an encryption without independent decryption is useless.

I'm not that technical and have used the cloudberry explorer app to access my files on S3 and then I've used your tool to decrypt.  All worked successfully.

The only problem I had was that the GUI window didn't display all of the buttons so I had to guess which one did what and therefore what to enter and press.  I'm running on Windows 10 64bit and have downloaded java 8 (update 211).

Not an urgent fix but if you do get chance to take a look I'd be grateful.

BR,
Phil

**Comment by Mikiya83** [comment]
Hi
Can you do some screenshots to see the problems ? 
What is your screen resolution ?

**Comment by mole-py** [comment]
Hi,
I've tested the app v1.6.1 today, and definitely has something to do with the resolution.
I've tried on a laptop with maximum resolution of 1366x768, the bottom part is trimmed horizontally, it shows up to half of the Destination box, nothing below.
As you mentioned resolution in this thread, I changed to 800x600, and it showed the Source box only, nothing below.
I hope it helps.

Thanks

**Comment by Discostu36** [comment]
I have the same problem, here's a screenshot: 
![image](https://user-images.githubusercontent.com/30999326/91151279-c239d980-e6bd-11ea-8205-2cfc8bfcbe8d.png)

I have the problem on both of my screens who have different resolutions and DPI settings

Version 1.6.1
Windows 10
Java Version 8 Update 261

**Edit:** Sorry, I missed the information about ResizeEnable in the readme. Maybe this option should be active by default?

**Comment by Mikiya83** [comment]
Enabling resize by default can lead to other "bugs" or can be quite "disturbing" (let's be honnest, the resize is quite ugly !). But if there are too many people with this problem i can enable it by default... (i can't fix the root problem, it's a Swing problem, the only solution would be to rewrite it to a more modern GUI Lib)

@mole-py 
Have you try :

You can start the GUI as a resizable window, with "r" command-line argument, or simply create a file "resizeEnable" in the same directory as hybrid_backup_sync_decipher_XXX_gui.jar.

**Comment by rjmsilveira** [comment]
I have the same issue as described. Resize enable worked and its ok now.
Thanks!

**Comment by Mikiya83** [comment]
Thanks for the feedback, i pinned this issue to help new users to find this workaround !
